# Generated by Django 4.1.2 on 2022-12-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='who',
            field=models.CharField(choices=[('Listener', 'Listener'), ('Singer', 'Singer')], default=('Listener', 'Listener'), max_length=15),
        ),
    ]
