# Generated by Django 4.1.2 on 2023-01-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_customuser_code_customuser_is_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
