# Generated by Django 4.1.2 on 2022-12-14 12:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicname', models.CharField(max_length=50)),
                ('mp3', models.FileField(upload_to='musics', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])])),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(choices=[('russian', 'russian'), ('uzbek', 'uzbek'), ('tadjik', 'tadjik'), ('kazak', 'kazak'), ('kavkaz', 'kavkaz')], default=('russian', 'russian'), max_length=50)),
            ],
            options={
                'verbose_name': 'Music',
                'verbose_name_plural': 'Musics',
            },
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Singer',
                'verbose_name_plural': 'Singers',
            },
        ),
        migrations.CreateModel(
            name='MyLikeSinger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singer_like', to='musics.singer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MyLikeSinger',
                'verbose_name_plural': 'MyLikeSingers',
            },
        ),
        migrations.CreateModel(
            name='MyLikeMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_time', models.DateTimeField(auto_now_add=True)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_for_music', to='musics.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MyLikeMusic',
                'verbose_name_plural': 'MyLikeMusics',
            },
        ),
        migrations.AddField(
            model_name='music',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_musics', to='musics.singer'),
        ),
        migrations.CreateModel(
            name='FollowsSinger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_singer', to='musics.singer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FollowsSinger',
                'verbose_name_plural': 'FollowsSingers',
            },
        ),
    ]
