# Generated by Django 4.1.2 on 2022-12-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylikesinger',
            name='yesno',
            field=models.BooleanField(default=True),
        ),
    ]
