# Generated by Django 4.1.2 on 2022-12-15 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0003_alter_singer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylikesinger',
            name='yesno',
        ),
        migrations.AlterField(
            model_name='mylikesinger',
            name='singer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='singer_like', to='musics.singer'),
        ),
    ]
