# Generated by Django 4.1.2 on 2022-12-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0007_alter_mylikesinger_singer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylikesinger',
            name='singer',
        ),
        migrations.AddField(
            model_name='mylikesinger',
            name='singer',
            field=models.ManyToManyField(related_name='singer_like', to='musics.singer'),
        ),
    ]
