# Generated by Django 4.1.2 on 2022-12-16 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musics', '0008_remove_mylikesinger_singer_mylikesinger_singer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylikesinger',
            name='singer',
        ),
        migrations.AlterField(
            model_name='mylikesinger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mylikesinger',
            name='singer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='singer_like', to='musics.singer'),
            preserve_default=False,
        ),
    ]
