# Generated by Django 4.1.2 on 2022-12-17 07:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musics', '0010_alter_mylikesinger_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followssinger',
            unique_together={('user', 'singer')},
        ),
        migrations.AlterUniqueTogether(
            name='mylikemusic',
            unique_together={('user', 'music')},
        ),
    ]
