# Generated by Django 4.1.2 on 2022-12-17 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musics', '0011_alter_followssinger_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ('-data_created',), 'verbose_name': 'Music', 'verbose_name_plural': 'Musics'},
        ),
        migrations.AlterModelOptions(
            name='mylikemusic',
            options={'ordering': ('-like_time',), 'verbose_name': 'MyLikeMusic', 'verbose_name_plural': 'MyLikeMusics'},
        ),
        migrations.CreateModel(
            name='MyPlayListMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_time', models.DateTimeField(auto_now_add=True)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_play_list', to='musics.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MyPlayListMusic',
                'verbose_name_plural': 'MyPlayListMusic',
                'ordering': ('-like_time',),
                'unique_together': {('user', 'music')},
            },
        ),
    ]
