# Generated by Django 4.1.2 on 2023-02-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0012_alter_music_options_alter_mylikemusic_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mylikemusic',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='mylikemusic',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mylikemusic',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
