# Generated by Django 4.1.2 on 2023-02-20 19:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musics', '0013_alter_mylikemusic_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mylikemusic',
            options={'ordering': ('-like_time',), 'verbose_name': 'MyLikeMusic', 'verbose_name_plural': 'MyLikeMusics'},
        ),
        migrations.AlterUniqueTogether(
            name='mylikemusic',
            unique_together={('user', 'music')},
        ),
        migrations.RemoveField(
            model_name='mylikemusic',
            name='count',
        ),
    ]
