# Generated by Django 4.1.2 on 2023-02-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0014_alter_mylikemusic_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylikemusic',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
