# Generated by Django 4.1.2 on 2023-02-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0016_alter_mylikemusic_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylikemusic',
            name='count',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
