# Generated by Django 4.1.2 on 2023-02-20 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0017_alter_mylikemusic_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylikemusic',
            name='count',
        ),
    ]
